# Конфигурация базы данных
datasource:
  host: localhost
  port: 5432
  name: spaced-repetition-bot-db
  username: postgres
  password: postgres
  schema: public
  maxPoolSize: 10

# gRPC порт
grpc:
  port: 50051

# HTTP порт для health-эндпоинтов
server:
  port: 8081